remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md
style: light
listen_for_clients_preferred_style: true
permalink: /:title/
footer: 'Copyright &copy; 2014-2020 Dorper'
